import React, { useMemo, useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  Archive,
  BarChart3,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  CircleAlert,
  Clock3,
  Edit3,
  History,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Lock,
  LockOpen,
  Settings2,
  Sparkles,
  TrendingUp,
  Users,
  X,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { LineChart as RLineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";
import { supabase } from "./src/lib/supabase";

const rolesSeed = [
  {
    id: "growth",
    name: "Growth Marketing",
    owner: "Dwi",
    mandate: "Keep the B2C engine aligned, measurable, and connected to revenue.",
  },
  {
    id: "activation",
    name: "Activation Specialist",
    owner: "Wina",
    mandate: "Move leads, conversations, and community activation so the pipeline does not go stale.",
  },
  {
    id: "learning",
    name: "Learning Operation",
    owner: "Fariz",
    mandate: "Ensure Academy products are ready, delivered well, and continuously improved.",
  },
  {
    id: "creative",
    name: "Graphic Designer & Editor",
    owner: "Annisa",
    mandate: "Keep priority campaign assets ready, consistent, and delivered on time.",
  },
];

const weekOptions = [
  { id: "w1", label: "3–7 June 2026", status: "locked", quarterWeek: "Week 1 of 13" },
  { id: "w2", label: "10–14 June 2026", status: "locked", quarterWeek: "Week 2 of 13" },
  { id: "w3", label: "17–21 June 2026", status: "current", quarterWeek: "Week 3 of 13" },
  { id: "w4", label: "24–28 June 2026", status: "planned", quarterWeek: "Week 4 of 13" },
];

const primaryNavItems = [
  { id: "home", label: "Home", icon: LayoutDashboard },
  { id: "kpi", label: "KPI Tracker", icon: BarChart3 },
  { id: "campaign", label: "Campaign Library", icon: Archive },
  { id: "business", label: "Business Performance", icon: TrendingUp },
  { id: "learningJourney", label: "Learning Journey", icon: Users },
];

const kpiSubNavItems = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "tracking", label: "Tracking", icon: ListChecks },
  { id: "history", label: "History", icon: History },
  { id: "weekly", label: "Review", icon: CalendarDays },
  { id: "monthly", label: "Monthly", icon: LineChart },
  { id: "setup", label: "Settings", icon: Settings2 },
];

const blockerOptions = [
  "No blocker",
  "Waiting for decision",
  "Waiting for asset/material",
  "Waiting for data",
  "Waiting for another role",
  "Unclear brief",
  "Timeline too tight",
  "Technical issue",
  "External dependency",
  "Overcapacity",
  "Low conversion",
  "Low inquiry quality",
  "Other",
];

const kpiDefinitions = [
  {
    id: "kpi-1",
    roleId: "growth",
    name: "Total B2C Revenue",
    description: "Total revenue generated by B2C products this week.",
    inputType: "currency_direct",
    displayType: "currency",
    target: 25000000,
    unit: "Rp",
  },
  {
    id: "kpi-2",
    roleId: "growth",
    name: "Revenue from Personal License + Assisted",
    description: "Revenue contribution from recurring/assisted product group.",
    inputType: "currency_direct",
    displayType: "currency",
    target: 10000000,
    unit: "Rp",
  },
  {
    id: "kpi-3",
    roleId: "growth",
    name: "Follow-up Rate",
    description: "Calculated from total active leads and leads followed up within SLA.",
    inputType: "calculated_rate",
    displayType: "percentage",
    numeratorLabel: "Leads followed up",
    denominatorLabel: "Total active leads",
    target: 90,
    unit: "%",
  },
  {
    id: "kpi-4",
    roleId: "growth",
    name: "Weekly Operating System Consistency",
    description: "Weekly rhythm, review, and decision log consistency.",
    inputType: "status",
    displayType: "status",
    target: "On Track",
  },
  {
    id: "kpi-5",
    roleId: "activation",
    name: "Qualified Leads Generated",
    description: "Qualified lead = clear product interest, valid contact, short need context, and logical next action.",
    inputType: "number_direct",
    displayType: "number",
    target: 12,
    unit: "leads",
  },
  {
    id: "kpi-6",
    roleId: "activation",
    name: "First Response Time",
    description: "Calculated from leads responded within SLA and total new inquiries.",
    inputType: "calculated_rate",
    displayType: "percentage",
    numeratorLabel: "Responded within SLA",
    denominatorLabel: "Total new inquiries",
    target: 90,
    unit: "%",
  },
  {
    id: "kpi-7",
    roleId: "activation",
    name: "Follow-up Completion Rate",
    description: "Calculated from leads with completed follow-up and total leads requiring follow-up.",
    inputType: "calculated_rate",
    displayType: "percentage",
    numeratorLabel: "Completed follow-up",
    denominatorLabel: "Leads requiring follow-up",
    target: 90,
    unit: "%",
  },
  {
    id: "kpi-8",
    roleId: "activation",
    name: "WA / Community Activation Consistency",
    description: "Number of meaningful WA/community activation activities this week.",
    inputType: "number_direct",
    displayType: "number",
    target: 2,
    unit: "activities",
  },
  {
    id: "kpi-9",
    roleId: "learning",
    name: "On-time Program Readiness",
    description: "Program assets, mentor, timeline, and operational preparation are ready on time.",
    inputType: "status",
    displayType: "status",
    target: "On Track",
  },
  {
    id: "kpi-10",
    roleId: "learning",
    name: "On-time Program Delivery",
    description: "Class or program delivery follows planned schedule and standard.",
    inputType: "status",
    displayType: "status",
    target: "On Track",
  },
  {
    id: "kpi-11",
    roleId: "learning",
    name: "Learner Satisfaction / Attendance Health",
    description: "Calculated from total attendees and total registered learners.",
    inputType: "calculated_rate",
    displayType: "percentage",
    numeratorLabel: "Attended learners",
    denominatorLabel: "Registered learners",
    target: 80,
    unit: "%",
  },
  {
    id: "kpi-12",
    roleId: "learning",
    name: "Feedback-to-Improvement Loop",
    description: "Feedback is collected, summarized, and converted into concrete improvement.",
    inputType: "checklist",
    displayType: "percentage",
    target: 100,
    checklistItems: ["Feedback collected", "Key issue summarized", "Improvement action defined", "Owner assigned"],
    unit: "%",
  },
  {
    id: "kpi-13",
    roleId: "creative",
    name: "On-time Creative Delivery",
    description: "Calculated from assets delivered on time and total assets due this week.",
    inputType: "calculated_rate",
    displayType: "percentage",
    numeratorLabel: "Assets delivered on time",
    denominatorLabel: "Total assets due",
    target: 90,
    unit: "%",
  },
  {
    id: "kpi-14",
    roleId: "creative",
    name: "Asset Readiness for P0 Campaign",
    description: "Readiness of priority campaign assets before campaign window.",
    inputType: "status",
    displayType: "status",
    target: "On Track",
  },
  {
    id: "kpi-15",
    roleId: "creative",
    name: "Weekly Production Consistency",
    description: "Number of priority assets completed this week.",
    inputType: "number_direct",
    displayType: "number",
    target: 8,
    unit: "assets",
  },
  {
    id: "kpi-16",
    roleId: "creative",
    name: "Revision Efficiency",
    description: "Average revision cycle remains efficient and not repetitive. Lower is better.",
    inputType: "number_direct_lower_is_better",
    displayType: "number",
    target: 2,
    unit: "cycles",
  },
];

const entriesSeed = [
  // Week 1 locked
  ...makeWeekEntries("w1", {
    "kpi-1": { actual: 21000000, notes: "Academy carried the week.", blocker: "Low conversion", nextAction: "Retarget warm leads.", updatedBy: "Dwi" },
    "kpi-2": { actual: 3800000, notes: "Assisted flow still unclear.", blocker: "Waiting for decision", nextAction: "Clarify offer ladder.", updatedBy: "Dwi" },
    "kpi-3": { numerator: 29, denominator: 44, notes: "Follow-up slipped near end of week.", blocker: "Overcapacity", nextAction: "Batch follow-up twice weekly.", updatedBy: "Dwi" },
    "kpi-4": { actual: "Needs Attention", notes: "Meeting happened, decision notes incomplete.", blocker: "Timeline too tight", nextAction: "Use review page live.", updatedBy: "Dwi" },
    "kpi-5": { actual: 8, notes: "Lead quality mixed.", blocker: "Low inquiry quality", nextAction: "Improve CTA qualification.", updatedBy: "Wina" },
    "kpi-6": { numerator: 36, denominator: 42, notes: "Mostly under 24h.", blocker: "No blocker", nextAction: "Maintain response window.", updatedBy: "Wina" },
    "kpi-7": { numerator: 24, denominator: 42, notes: "Some free class leads stale.", blocker: "Overcapacity", nextAction: "Hot lead priority.", updatedBy: "Wina" },
    "kpi-8": { actual: 1, notes: "Only one WA activation.", blocker: "Waiting for asset/material", nextAction: "Prepare weekly WA kit.", updatedBy: "Wina" },
    "kpi-9": { actual: "On Track", notes: "Program ready.", blocker: "No blocker", nextAction: "Maintain checklist.", updatedBy: "Fariz" },
    "kpi-10": { actual: "On Track", notes: "Delivery stable.", blocker: "No blocker", nextAction: "Maintain.", updatedBy: "Fariz" },
    "kpi-11": { numerator: 32, denominator: 42, notes: "Attendance acceptable.", blocker: "No blocker", nextAction: "Add reminder H-1.", updatedBy: "Fariz" },
    "kpi-12": { checklist: [true, true, false, false], notes: "Feedback collected but not converted.", blocker: "Waiting for decision", nextAction: "Assign owner.", updatedBy: "Fariz" },
    "kpi-13": { numerator: 7, denominator: 9, notes: "Late brief affected output.", blocker: "Unclear brief", nextAction: "Lock brief H-5.", updatedBy: "Annisa" },
    "kpi-14": { actual: "Needs Attention", notes: "P0 direction shifted.", blocker: "Waiting for decision", nextAction: "Freeze direction before production.", updatedBy: "Annisa" },
    "kpi-15": { actual: 7, notes: "One asset postponed.", blocker: "Waiting for asset/material", nextAction: "Prioritize P0 queue.", updatedBy: "Annisa" },
    "kpi-16": { actual: 3, notes: "Too many back-and-forth revisions.", blocker: "Unclear brief", nextAction: "Improve first brief.", updatedBy: "Annisa" },
  }),
  // Week 2 locked
  ...makeWeekEntries("w2", {
    "kpi-1": { actual: 22950000, notes: "Revenue improved from last week.", blocker: "Low conversion", nextAction: "Push Academy closing window.", updatedBy: "Dwi" },
    "kpi-2": { actual: 5200000, notes: "Some Assisted interest converted.", blocker: "Low conversion", nextAction: "Use proof asset in follow-up.", updatedBy: "Dwi" },
    "kpi-3": { numerator: 38, denominator: 50, notes: "Better completion but still below target.", blocker: "Overcapacity", nextAction: "Reduce low-intent follow-up.", updatedBy: "Dwi" },
    "kpi-4": { actual: "On Track", notes: "Weekly review completed.", blocker: "No blocker", nextAction: "Maintain review ritual.", updatedBy: "Dwi" },
    "kpi-5": { actual: 10, notes: "Lead intake improved.", blocker: "Low inquiry quality", nextAction: "Add qualifying question.", updatedBy: "Wina" },
    "kpi-6": { numerator: 41, denominator: 45, notes: "Response time healthy.", blocker: "No blocker", nextAction: "Maintain.", updatedBy: "Wina" },
    "kpi-7": { numerator: 34, denominator: 48, notes: "Follow-up backlog reduced.", blocker: "Overcapacity", nextAction: "Daily 30-min follow-up block.", updatedBy: "Wina" },
    "kpi-8": { actual: 2, notes: "Two community touches done.", blocker: "No blocker", nextAction: "Test testimonial angle.", updatedBy: "Wina" },
    "kpi-9": { actual: "On Track", notes: "Prep stable.", blocker: "No blocker", nextAction: "Mentor brief.", updatedBy: "Fariz" },
    "kpi-10": { actual: "On Track", notes: "Class delivered well.", blocker: "No blocker", nextAction: "Maintain.", updatedBy: "Fariz" },
    "kpi-11": { numerator: 34, denominator: 40, notes: "Attendance improved.", blocker: "No blocker", nextAction: "Keep reminder flow.", updatedBy: "Fariz" },
    "kpi-12": { checklist: [true, true, true, false], notes: "Improvement action defined, owner not assigned yet.", blocker: "Waiting for decision", nextAction: "Assign improvement owner.", updatedBy: "Fariz" },
    "kpi-13": { numerator: 8, denominator: 9, notes: "Almost on target.", blocker: "Unclear brief", nextAction: "Brief checklist.", updatedBy: "Annisa" },
    "kpi-14": { actual: "Needs Attention", notes: "P0 campaign asset still needs earlier lock.", blocker: "Waiting for decision", nextAction: "Confirm direction earlier.", updatedBy: "Annisa" },
    "kpi-15": { actual: 8, notes: "Production met target.", blocker: "No blocker", nextAction: "Maintain.", updatedBy: "Annisa" },
    "kpi-16": { actual: 2, notes: "Revision cycle healthy.", blocker: "No blocker", nextAction: "Maintain.", updatedBy: "Annisa" },
  }),
  // Week 3 current
  ...makeWeekEntries("w3", {
    "kpi-1": { actual: 18750000, notes: "Academy moving, Personal License still below target.", blocker: "Low conversion", nextAction: "Prioritize Personal License Business retargeting and assisted follow-up.", updatedBy: "Dwi" },
    "kpi-2": { actual: 4200000, notes: "Assisted interest exists, but closing path is still not firm.", blocker: "Waiting for decision", nextAction: "Lock Assisted offer flow and clarify follow-up ownership.", updatedBy: "Dwi" },
    "kpi-3": { numerator: 38, denominator: 50, notes: "Several leads from WA were followed up late.", blocker: "Overcapacity", nextAction: "Focus only on hot leads and define follow-up batch time.", updatedBy: "Dwi" },
    "kpi-4": { actual: "Needs Attention", notes: "Weekly meeting happened, but decision log was incomplete.", blocker: "Timeline too tight", nextAction: "Use Weekly Review page during meeting, not after meeting.", updatedBy: "Dwi" },
    "kpi-5": { actual: 9, notes: "Most leads came from WA Community and Academy inquiries.", blocker: "Low inquiry quality", nextAction: "Tighten CTA and ask one qualification question before routing.", updatedBy: "Wina" },
    "kpi-6": { numerator: 40, denominator: 43, notes: "Most inquiries were responded to within 24 hours.", blocker: "No blocker", nextAction: "Maintain response block twice per day.", updatedBy: "Wina" },
    "kpi-7": { numerator: 31, denominator: 49, notes: "Some leads became stale after free class.", blocker: "Overcapacity", nextAction: "Prioritize hot leads first and close stale leads with final CTA.", updatedBy: "Wina" },
    "kpi-8": { actual: 2, notes: "One education post and one offer reminder sent.", blocker: "No blocker", nextAction: "Add testimonial format next week.", updatedBy: "Wina" },
    "kpi-9": { actual: "On Track", notes: "Location Analytics prep is stable.", blocker: "No blocker", nextAction: "Confirm mentor brief for next session.", updatedBy: "Fariz" },
    "kpi-10": { actual: "On Track", notes: "No delivery issue this week.", blocker: "No blocker", nextAction: "Maintain class checklist.", updatedBy: "Fariz" },
    "kpi-11": { numerator: 34, denominator: 41, notes: "Attendance is healthy, but some participants requested clearer hands-on steps.", blocker: "No blocker", nextAction: "Improve hands-on instruction clarity.", updatedBy: "Fariz" },
    "kpi-12": { checklist: [true, true, false, false], notes: "Feedback collected but not yet converted into implementation action.", blocker: "Waiting for decision", nextAction: "Pick top 3 issues and assign improvement owner.", updatedBy: "Fariz" },
    "kpi-13": { numerator: 8, denominator: 9, notes: "One campaign asset was delayed due to late brief.", blocker: "Unclear brief", nextAction: "Require H-5 locked brief for P0 assets.", updatedBy: "Annisa" },
    "kpi-14": { actual: "Needs Attention", notes: "Some visual direction was still changing near launch.", blocker: "Waiting for decision", nextAction: "Confirm campaign direction before production starts.", updatedBy: "Annisa" },
    "kpi-15": { actual: 8, notes: "Production volume met the weekly target.", blocker: "No blocker", nextAction: "Keep production queue focused on P0 products.", updatedBy: "Annisa" },
    "kpi-16": { actual: 2, notes: "Most assets completed within two revision cycles.", blocker: "No blocker", nextAction: "Maintain clear first brief standard.", updatedBy: "Annisa" },
  }),
];

function makeWeekEntries(weekId, values) {
  return Object.entries(values).map(([kpiId, data]) => ({
    id: `${weekId}-${kpiId}`,
    weekId,
    kpiId,
    ...data,
    updatedAt: "2026-06-19T09:00:00.000Z",
  }));
}

function getDefinition(kpiId, kpis = []) {
  return kpis.find((k) => k.id === kpiId) || kpiDefinitions.find((k) => k.id === kpiId);
}

function computeActual(def, entry) {
  if (!entry) return null;
  if (def.inputType === "calculated_rate") {
    if (!entry.denominator) return 0;
    return Math.round((Number(entry.numerator || 0) / Number(entry.denominator || 0)) * 100);
  }
  if (def.inputType === "checklist") {
    const total = def.checklistItems?.length || 1;
    const done = (entry.checklist || []).filter(Boolean).length;
    return Math.round((done / total) * 100);
  }
  return entry.actual;
}

function getStatus(def, entry) {
  if (!entry) return "pending";
  const actual = computeActual(def, entry);
  if (actual === undefined || actual === null || actual === "") return "pending";
  if (def.inputType === "status") {
    if (actual === "On Track") return "green";
    if (actual === "Needs Attention") return "yellow";
    return "red";
  }
  if (def.inputType === "number_direct_lower_is_better") {
    if (Number(actual) <= Number(def.target)) return "green";
    if (Number(actual) <= Number(def.target) + 1) return "yellow";
    return "red";
  }
  const ratio = Number(actual) / Number(def.target);
  if (ratio >= 1) return "green";
  if (ratio >= 0.7) return "yellow";
  return "red";
}

function statusLabel(status) {
  return {
    green: "On track",
    yellow: "Needs attention",
    red: "Off track",
    pending: "Pending",
  }[status];
}

function statusClass(status) {
  return {
    green: "bg-emerald-50 text-emerald-700 ring-emerald-100",
    yellow: "bg-amber-50 text-amber-700 ring-amber-100",
    red: "bg-rose-50 text-rose-700 ring-rose-100",
    pending: "bg-neutral-100 text-neutral-500 ring-neutral-200",
  }[status];
}

function StatusPill({ status }) {
  return (
    <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-medium ring-1 ${statusClass(status)}`}>
      <span className="mr-1.5 h-1.5 w-1.5 rounded-full bg-current" />
      {statusLabel(status)}
    </span>
  );
}

function formatValue(def, entryOrValue, rawValue = false) {
  const value = rawValue ? entryOrValue : computeActual(def, entryOrValue);
  if (value === null || value === undefined || value === "") return "—";
  if (def.displayType === "currency") return `Rp${Number(value || 0).toLocaleString("id-ID")}`;
  if (def.displayType === "percentage") return `${value}%`;
  if (def.displayType === "number") return `${value} ${def.unit || ""}`.trim();
  return value;
}

function displayFormula(def, entry) {
  if (!entry) return "No update yet";
  if (def.inputType === "calculated_rate") return `${entry.numerator || 0} / ${entry.denominator || 0}`;
  if (def.inputType === "checklist") return `${(entry.checklist || []).filter(Boolean).length} / ${def.checklistItems.length} completed`;
  return "Direct input";
}

function getEntriesForWeek(entries, weekId, kpis = kpiDefinitions) {
  return kpis.map((def) => ({ def, entry: entries.find((e) => e.weekId === weekId && e.kpiId === def.id) }));
}

function getActivePrimary(active) {
  if (["dashboard", "tracking", "history", "weekly", "monthly", "setup"].includes(active)) return "kpi";
  return active;
}

function Header({ active, setActive, weekId, setWeekId, weeks }) {
  const week = weeks.find((w) => w.id === weekId);
  const activePrimary = getActivePrimary(active);
  const showKpiSubnav = activePrimary === "kpi";

  function handlePrimaryClick(id) {
    if (id === "kpi") return setActive("dashboard");
    return setActive(id);
  }

  return (
    <div className="sticky top-0 z-30 border-b border-black/5 bg-[#f5f5f7]/80 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
        <button onClick={() => setActive("home")} className="flex items-center gap-3 rounded-3xl pr-3 text-left transition hover:opacity-75">
          <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-black text-white shadow-sm">
            <Sparkles size={18} />
          </div>
          <div>
            <div className="text-sm font-semibold tracking-tight text-[#1d1d1f]">MAPID B2C</div>
            <div className="text-xs text-[#6e6e73]">Growth Operating System · MVP</div>
          </div>
        </button>

        <nav className="hidden items-center gap-1 rounded-full bg-white/90 p-1 shadow-sm ring-1 ring-black/5 lg:flex">
          {primaryNavItems.map((item) => {
            const Icon = item.icon;
            const selected = activePrimary === item.id;
            return (
              <button
                key={item.id}
                onClick={() => handlePrimaryClick(item.id)}
                className={`flex items-center gap-2 rounded-full px-4 py-2 text-sm transition ${
                  selected ? "bg-black text-white" : "text-[#6e6e73] hover:bg-neutral-100 hover:text-[#1d1d1f]"
                }`}
              >
                <Icon size={15} />
                <span className="hidden xl:inline">{item.label}</span>
                <span className="xl:hidden">{item.label.split(" ")[0]}</span>
              </button>
            );
          })}
        </nav>

        <div className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm shadow-sm ring-1 ring-black/5">
          {week?.status === "locked" ? <Lock size={15} className="text-[#6e6e73]" /> : <Clock3 size={15} className="text-[#6e6e73]" />}
          <select value={weekId} onChange={(e) => setWeekId(e.target.value)} className="max-w-[150px] bg-transparent text-[#1d1d1f] outline-none md:max-w-none">
            {weeks.map((w) => (
              <option key={w.id} value={w.id}>{w.label}</option>
            ))}
          </select>
          <ChevronDown size={14} className="text-[#6e6e73]" />
        </div>
      </div>

      <div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto px-6 pb-4 lg:hidden">
        {primaryNavItems.map((item) => {
          const Icon = item.icon;
          const selected = activePrimary === item.id;
          return (
            <button
              key={item.id}
              onClick={() => handlePrimaryClick(item.id)}
              className={`flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm transition ${
                selected ? "bg-black text-white" : "bg-white text-[#6e6e73] ring-1 ring-black/5"
              }`}
            >
              <Icon size={15} />
              {item.label}
            </button>
          );
        })}
      </div>

      {showKpiSubnav && (
        <div className="border-t border-black/[0.03] bg-[#f5f5f7]/60">
          <div className="mx-auto flex max-w-7xl items-center gap-2 overflow-x-auto px-6 py-3">
            <div className="mr-2 hidden text-xs font-medium uppercase tracking-wide text-[#a1a1a6] md:block">KPI</div>
            {kpiSubNavItems.map((item) => {
              const selected = active === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => setActive(item.id)}
                  className={`shrink-0 rounded-full px-3.5 py-1.5 text-sm transition ${
                    selected ? "bg-white text-[#1d1d1f] shadow-sm ring-1 ring-black/5" : "text-[#6e6e73] hover:text-[#1d1d1f]"
                  }`}
                >
                  {item.label}
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

function PageShell({ title, eyebrow, description, children }) {
  return (
    <motion.main
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
      className="mx-auto max-w-7xl px-6 py-10"
    >
      <div className="mb-8 max-w-3xl">
        <div className="mb-3 text-sm font-medium text-[#6e6e73]">{eyebrow}</div>
        <h1 className="text-4xl font-semibold tracking-tight text-[#1d1d1f] md:text-5xl">{title}</h1>
        <p className="mt-4 text-base leading-7 text-[#6e6e73]">{description}</p>
      </div>
      {children}
    </motion.main>
  );
}

function StatCard({ label, value, caption, icon: Icon }) {
  return (
    <Card className="rounded-[28px] border-black/5 bg-white shadow-sm">
      <CardContent className="p-6">
        <div className="mb-5 flex items-center justify-between">
          <div className="text-sm text-[#6e6e73]">{label}</div>
          {Icon && <Icon size={18} className="text-[#a1a1a6]" />}
        </div>
        <div className="text-3xl font-semibold tracking-tight text-[#1d1d1f]">{value}</div>
        {caption && <div className="mt-2 text-sm text-[#6e6e73]">{caption}</div>}
      </CardContent>
    </Card>
  );
}

function Dashboard({ roles, entries, weekId, setActive, setSelectedRole, weeks, kpis }) {
  const week = weeks.find((w) => w.id === weekId);
  const rows = getEntriesForWeek(entries, weekId, kpis);
  const summary = useMemo(() => {
    const statuses = rows.map(({ def, entry }) => getStatus(def, entry));
    return {
      total: rows.length,
      updated: statuses.filter((s) => s !== "pending").length,
      green: statuses.filter((s) => s === "green").length,
      yellow: statuses.filter((s) => s === "yellow").length,
      red: statuses.filter((s) => s === "red").length,
      pending: statuses.filter((s) => s === "pending").length,
    };
  }, [rows]);

  const blockers = useMemo(() => {
    const counts = {};
    rows.forEach(({ def, entry }) => {
      const status = getStatus(def, entry);
      if ((status === "yellow" || status === "red") && entry?.blocker) counts[entry.blocker] = (counts[entry.blocker] || 0) + 1;
    });
    return Object.entries(counts).sort((a, b) => b[1] - a[1]);
  }, [rows]);

  return (
    <PageShell
      eyebrow={`${week.quarterWeek} · ${week.status === "locked" ? "Historical week locked" : week.status === "current" ? "Current editable week" : "Planned week"}`}
      title="Track the week. Protect the history."
      description="Current week can be updated. Completed weeks are treated as historical records so quarterly progress stays trustworthy."
    >
      <div className="mb-6 rounded-[30px] bg-white p-5 shadow-sm ring-1 ring-black/5">
        <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
          <div className="flex items-center gap-3">
            <div className={`rounded-2xl p-3 ${week.status === "locked" ? "bg-neutral-100 text-neutral-600" : "bg-emerald-50 text-emerald-700"}`}>
              {week.status === "locked" ? <Lock size={20} /> : <LockOpen size={20} />}
            </div>
            <div>
              <div className="font-semibold text-[#1d1d1f]">{week.label}</div>
              <div className="text-sm text-[#6e6e73]">
                {week.status === "locked" ? "View-only historical data" : week.status === "current" ? "Editable until weekly review is completed" : "No data yet"}
              </div>
            </div>
          </div>
          <Button onClick={() => setActive("history")} variant="secondary" className="rounded-full bg-[#f5f5f7] hover:bg-neutral-200">
            <TrendingUp size={16} className="mr-2" /> View KPI Trends
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        <StatCard label="KPI Updated" value={`${summary.updated}/${summary.total}`} caption="Selected week" icon={CheckCircle2} />
        <StatCard label="On Track" value={summary.green} caption="Green KPI" icon={BarChart3} />
        <StatCard label="Needs Attention" value={summary.yellow} caption="Yellow KPI" icon={CircleAlert} />
        <StatCard label="Off Track" value={summary.red} caption="Red KPI" icon={CircleAlert} />
        <StatCard label="Pending Update" value={summary.pending} caption="Not yet updated" icon={Clock3} />
      </div>

      <div className="mt-8 grid gap-5 lg:grid-cols-4">
        {roles.map((role) => {
          const roleRows = rows.filter(({ def }) => def.roleId === role.id);
          const statuses = roleRows.map(({ def, entry }) => getStatus(def, entry));
          const hasRed = statuses.includes("red");
          const hasYellow = statuses.includes("yellow");
          const roleStatus = hasRed ? "red" : hasYellow ? "yellow" : statuses.includes("pending") ? "pending" : "green";
          const issue = roleRows.find(({ def, entry }) => ["red", "yellow"].includes(getStatus(def, entry)));
          const mainBlocker = issue?.entry?.blocker || "No blocker";
          const nextAction = issue?.entry?.nextAction || "Maintain current rhythm.";

          return (
            <Card key={role.id} className="group rounded-[30px] border-black/5 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md">
              <CardContent className="p-6">
                <div className="mb-5 flex items-start justify-between gap-3">
                  <div>
                    <div className="text-lg font-semibold tracking-tight text-[#1d1d1f]">{role.name}</div>
                    <div className="mt-1 text-sm text-[#6e6e73]">Owner: {role.owner}</div>
                  </div>
                  <StatusPill status={roleStatus} />
                </div>
                <div className="rounded-3xl bg-[#f5f5f7] p-4">
                  <div className="grid grid-cols-3 gap-3 text-center">
                    <MiniNumber label="Green" value={statuses.filter((s) => s === "green").length} tone="green" />
                    <MiniNumber label="Yellow" value={statuses.filter((s) => s === "yellow").length} tone="yellow" />
                    <MiniNumber label="Red" value={statuses.filter((s) => s === "red").length} tone="red" />
                  </div>
                </div>
                <div className="mt-5 space-y-3">
                  <InfoBlock label="Main blocker" value={mainBlocker} />
                  <InfoBlock label="Next action" value={nextAction} clamp />
                </div>
                <Button
                  onClick={() => {
                    setSelectedRole(role.id);
                    setActive("tracking");
                  }}
                  className="mt-6 w-full rounded-full bg-black text-white hover:bg-black/90"
                >
                  View / Update KPI
                </Button>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="mt-8 grid gap-5 lg:grid-cols-3">
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm lg:col-span-2">
          <CardContent className="p-6">
            <div className="mb-5 flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">KPI needing attention</h2>
                <p className="mt-1 text-sm text-[#6e6e73]">Rates show numerator/denominator so the team understands the scale behind the percentage.</p>
              </div>
              <CircleAlert className="text-[#a1a1a6]" size={20} />
            </div>
            <div className="space-y-3">
              {rows
                .filter(({ def, entry }) => ["yellow", "red"].includes(getStatus(def, entry)))
                .slice(0, 6)
                .map(({ def, entry }) => {
                  const role = roles.find((r) => r.id === def.roleId);
                  return (
                    <div key={def.id} className="flex flex-col justify-between gap-3 rounded-3xl bg-[#f5f5f7] p-4 md:flex-row md:items-center">
                      <div>
                        <div className="text-sm font-semibold text-[#1d1d1f]">{def.name}</div>
                        <div className="mt-1 text-sm text-[#6e6e73]">{role?.name} · {displayFormula(def, entry)} · {entry?.blocker}</div>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="text-sm font-semibold text-[#1d1d1f]">{formatValue(def, entry)}</div>
                        <StatusPill status={getStatus(def, entry)} />
                      </div>
                    </div>
                  );
                })}
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">Blocker pattern</h2>
            <p className="mt-1 text-sm text-[#6e6e73]">Most repeated friction this week.</p>
            <div className="mt-5 space-y-3">
              {blockers.length ? blockers.map(([blocker, count]) => (
                <div key={blocker} className="flex items-center justify-between rounded-2xl bg-[#f5f5f7] px-4 py-3">
                  <span className="text-sm text-[#1d1d1f]">{blocker}</span>
                  <span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-[#6e6e73]">{count}</span>
                </div>
              )) : <div className="rounded-2xl bg-[#f5f5f7] p-4 text-sm text-[#6e6e73]">No blocker recorded.</div>}
            </div>
          </CardContent>
        </Card>
      </div>
    </PageShell>
  );
}

function MiniNumber({ label, value, tone }) {
  const cls = tone === "green" ? "text-emerald-600" : tone === "yellow" ? "text-amber-500" : "text-rose-500";
  return <div><div className={`text-xl font-semibold ${cls}`}>{value}</div><div className="text-[11px] text-[#6e6e73]">{label}</div></div>;
}

function InfoBlock({ label, value, clamp }) {
  return <div><div className="text-xs font-medium uppercase tracking-wide text-[#a1a1a6]">{label}</div><div className={`mt-1 text-sm leading-6 text-[#6e6e73] ${clamp ? "line-clamp-2" : ""}`}>{value}</div></div>;
}

function KpiTracking({ roles, entries, setEntries, weekId, selectedRole, setSelectedRole, weeks, kpis }) {
  const [editing, setEditing] = useState(null);
  const week = weeks.find((w) => w.id === weekId);
  const isLocked = week.status === "locked";
  const rows = getEntriesForWeek(entries, weekId, kpis).filter(({ def }) => selectedRole === "all" || def.roleId === selectedRole);

  return (
    <PageShell
      eyebrow={isLocked ? "Historical week · view only" : "Current weekly input"}
      title={isLocked ? "This week is locked as historical record." : "Input the real components behind each KPI."}
      description={isLocked ? "Past weeks can be reviewed but not freely changed. Use correction notes in the final product if historical data needs adjustment." : "Percentage KPIs are calculated from their numerator and denominator so the team can trust the context behind the final rate."}
    >
      <div className="mb-5 flex flex-col justify-between gap-3 rounded-[30px] bg-white p-4 shadow-sm ring-1 ring-black/5 md:flex-row md:items-center">
        <div className="flex items-center gap-3 px-2">
          {isLocked ? <Lock size={18} className="text-[#6e6e73]" /> : <Users size={18} className="text-[#6e6e73]" />}
          <span className="text-sm font-medium text-[#1d1d1f]">{isLocked ? "Locked historical data" : "Role filter"}</span>
        </div>
        <select value={selectedRole} onChange={(e) => setSelectedRole(e.target.value)} className="rounded-full bg-[#f5f5f7] px-5 py-3 text-sm text-[#1d1d1f] outline-none">
          <option value="all">All Roles</option>
          {roles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}
        </select>
      </div>

      <Card className="overflow-hidden rounded-[30px] border-black/5 bg-white shadow-sm">
        <CardContent className="p-0">
          <div className="hidden grid-cols-[1.1fr_1.4fr_1fr_1fr_.9fr_1fr_.7fr] gap-4 border-b border-black/5 px-6 py-4 text-xs font-semibold uppercase tracking-wide text-[#a1a1a6] lg:grid">
            <div>Role</div><div>KPI</div><div>Input structure</div><div>Actual</div><div>Status</div><div>Blocker</div><div></div>
          </div>
          <div className="divide-y divide-black/5">
            {rows.map(({ def, entry }) => {
              const role = roles.find((r) => r.id === def.roleId);
              return (
                <div key={def.id} className="grid gap-4 px-6 py-5 lg:grid-cols-[1.1fr_1.4fr_1fr_1fr_.9fr_1fr_.7fr] lg:items-center">
                  <div><div className="text-sm font-medium text-[#1d1d1f]">{role?.name}</div><div className="mt-1 text-xs text-[#6e6e73]">{role?.owner}</div></div>
                  <div><div className="text-sm font-semibold text-[#1d1d1f]">{def.name}</div><div className="mt-1 line-clamp-2 text-xs leading-5 text-[#6e6e73]">{def.description}</div></div>
                  <div><div className="text-sm text-[#1d1d1f]">{inputTypeLabel(def)}</div><div className="mt-1 text-xs text-[#6e6e73]">Target: {formatTarget(def)}</div></div>
                  <div><div className="text-sm font-semibold text-[#1d1d1f]">{formatValue(def, entry)}</div><div className="mt-1 text-xs text-[#6e6e73]">{displayFormula(def, entry)}</div></div>
                  <div><StatusPill status={getStatus(def, entry)} /></div>
                  <div className="text-sm text-[#6e6e73]">{entry?.blocker || "—"}</div>
                  <div className="flex justify-end">
                    <Button disabled={isLocked} onClick={() => setEditing({ def, entry })} variant="secondary" className={`rounded-full ${isLocked ? "cursor-not-allowed bg-neutral-100 text-neutral-400" : "bg-[#f5f5f7] hover:bg-neutral-200"}`}>
                      {isLocked ? <Lock size={14} className="mr-2" /> : <Edit3 size={14} className="mr-2" />} {isLocked ? "Locked" : "Edit"}
                    </Button>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {editing && <EditModal payload={editing} weekId={weekId} onClose={() => setEditing(null)} setEntries={setEntries} />}
    </PageShell>
  );
}

function inputTypeLabel(def) {
  if (def.inputType === "calculated_rate") return "Calculated rate";
  if (def.inputType === "checklist") return "Checklist progress";
  if (def.inputType === "status") return "Status selection";
  if (def.inputType === "currency_direct") return "Direct revenue input";
  if (def.inputType === "number_direct_lower_is_better") return "Direct number · lower better";
  return "Direct number input";
}

function formatTarget(def) {
  if (def.displayType === "currency") return `Rp${Number(def.target).toLocaleString("id-ID")}`;
  if (def.displayType === "percentage") return `${def.target}%`;
  if (def.displayType === "number") return `${def.target} ${def.unit || ""}`.trim();
  return def.target;
}

function EditModal({ payload, weekId, onClose, setEntries }) {
  const { def, entry } = payload;
  const [draft, setDraft] = useState(entry ? { ...entry } : { weekId, kpiId: def.id, blocker: "No blocker", updatedBy: "Dwi", notes: "", nextAction: "" });
  const status = getStatus(def, draft);
  const needsContext = status === "yellow" || status === "red";
  const isValidationFailed = needsContext && (!draft.blocker || draft.blocker === "No blocker" || !draft.nextAction?.trim());
  const [saving, setSaving] = useState(false);
  const [errorMsg, setErrorMsg] = useState(null);

  async function save() {
    if (isValidationFailed) return;
    setSaving(true);
    setErrorMsg(null);
    try {
      const dbPayload = {
        week_id: weekId,
        kpi_id: def.id,
        notes: draft.notes || "",
        blocker: draft.blocker || "No blocker",
        next_action: draft.nextAction || "",
        updated_by: draft.updatedBy || "Dwi",
        updated_at: new Date().toISOString()
      };

      if (def.inputType === "status") {
        dbPayload.actual_status = draft.actual || "On Track";
        dbPayload.actual_value = null;
      } else if (def.inputType === "calculated_rate") {
        dbPayload.numerator_value = draft.numerator !== null && draft.numerator !== undefined ? Number(draft.numerator) : null;
        dbPayload.denominator_value = draft.denominator !== null && draft.denominator !== undefined ? Number(draft.denominator) : null;
      } else if (def.inputType === "checklist") {
        dbPayload.checklist_values = draft.checklist || [];
      } else {
        dbPayload.actual_value = draft.actual !== null && draft.actual !== undefined ? Number(draft.actual) : null;
        dbPayload.actual_status = null;
      }

      if (draft.id && !draft.id.includes('-')) {
        dbPayload.id = draft.id;
      }

      const { data, error } = await supabase
        .from("kpi_entries")
        .upsert(dbPayload, { onConflict: "week_id, kpi_id" })
        .select("*");

      if (error) throw error;

      const returnedRow = data[0];
      const updatedEntry = {
        id: returnedRow.id,
        weekId: returnedRow.week_id,
        kpiId: returnedRow.kpi_id,
        actual: def.inputType === 'status' ? returnedRow.actual_status : (returnedRow.actual_value !== null ? Number(returnedRow.actual_value) : null),
        numerator: returnedRow.numerator_value !== null ? Number(returnedRow.numerator_value) : null,
        denominator: returnedRow.denominator_value !== null ? Number(returnedRow.denominator_value) : null,
        checklist: returnedRow.checklist_values || null,
        notes: returnedRow.notes,
        blocker: returnedRow.blocker,
        nextAction: returnedRow.next_action,
        updatedBy: returnedRow.updated_by,
        updatedAt: returnedRow.updated_at
      };

      setEntries((prev) => {
        const exists = prev.some((e) => e.weekId === weekId && e.kpiId === def.id);
        if (exists) return prev.map((e) => (e.weekId === weekId && e.kpiId === def.id ? updatedEntry : e));
        return [...prev, updatedEntry];
      });

      onClose();
    } catch (err) {
      console.error("Database save failed:", err);
      setErrorMsg(err.message || "Failed to save to database. Please check validation rules.");
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4 backdrop-blur-sm">
      <motion.div initial={{ opacity: 0, scale: 0.96, y: 8 }} animate={{ opacity: 1, scale: 1, y: 0 }} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[34px] bg-white p-6 shadow-2xl">
        <div className="mb-6 flex items-start justify-between gap-4">
          <div>
            <div className="mb-2 text-sm text-[#6e6e73]">{inputTypeLabel(def)}</div>
            <h2 className="text-2xl font-semibold tracking-tight text-[#1d1d1f]">{def.name}</h2>
            <p className="mt-2 text-sm leading-6 text-[#6e6e73]">{def.description}</p>
          </div>
          <button onClick={onClose} className="rounded-full bg-[#f5f5f7] p-2 text-[#6e6e73] hover:bg-neutral-200"><X size={18} /></button>
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          <div className="rounded-3xl bg-[#f5f5f7] p-4"><div className="text-xs font-medium uppercase tracking-wide text-[#a1a1a6]">Target</div><div className="mt-2 text-xl font-semibold text-[#1d1d1f]">{formatTarget(def)}</div></div>
          <div className="rounded-3xl bg-[#f5f5f7] p-4"><div className="text-xs font-medium uppercase tracking-wide text-[#a1a1a6]">Current result</div><div className="mt-2 text-xl font-semibold text-[#1d1d1f]">{formatValue(def, draft)}</div></div>
          <div className="rounded-3xl bg-[#f5f5f7] p-4"><div className="text-xs font-medium uppercase tracking-wide text-[#a1a1a6]">Status</div><div className="mt-2"><StatusPill status={status} /></div></div>
        </div>

        <div className="mt-5 grid gap-4">
          <ContextualInput def={def} draft={draft} setDraft={setDraft} />

          <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">Notes</span><textarea value={draft.notes || ""} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} rows={3} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none" /></label>

          <div className="grid gap-4 md:grid-cols-2">
            <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">Blocker {needsContext && <span className="text-rose-500">*</span>}</span><select value={draft.blocker || "No blocker"} onChange={(e) => setDraft({ ...draft, blocker: e.target.value })} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none">{blockerOptions.map((b) => <option key={b}>{b}</option>)}</select></label>
            <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">Updated by</span><select value={draft.updatedBy || "Dwi"} onChange={(e) => setDraft({ ...draft, updatedBy: e.target.value })} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none"><option>Dwi</option><option>Wina</option><option>Fariz</option><option>Annisa</option><option>Other</option></select></label>
          </div>

          <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">Next action {needsContext && <span className="text-rose-500">*</span>}</span><textarea value={draft.nextAction || ""} onChange={(e) => setDraft({ ...draft, nextAction: e.target.value })} rows={2} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none" /></label>
        </div>

        {needsContext && (
          <div className={`mt-5 rounded-3xl p-4 text-sm leading-6 ring-1 transition-all duration-200 ${isValidationFailed ? "bg-rose-50 text-rose-800 ring-rose-200/60" : "bg-amber-50 text-amber-800 ring-amber-200/60"}`}>
            {isValidationFailed ? (
              <div className="flex gap-2.5 items-start">
                <CircleAlert size={16} className="mt-1 shrink-0 text-rose-600" />
                <span><strong>Context Required:</strong> This KPI is currently not on track. The PRD rules require specifying a valid blocker (not "No blocker") and a concrete next action before saving.</span>
              </div>
            ) : (
              <div className="flex gap-2.5 items-start">
                <CheckCircle2 size={16} className="mt-1 shrink-0 text-emerald-600" />
                <span><strong>Context Complete:</strong> Required blocker and next action have been provided. The team is now equipped for review.</span>
              </div>
            )}
          </div>
        )}

        {errorMsg && (
          <div className="mt-5 rounded-3xl bg-rose-50 text-rose-800 p-4 text-sm leading-6 ring-1 ring-rose-200 flex gap-2.5 items-start">
            <CircleAlert size={16} className="mt-1 shrink-0 text-rose-600 animate-pulse" />
            <span><strong>Database Integrity Failure:</strong> {errorMsg}</span>
          </div>
        )}

        <div className="mt-6 flex justify-end gap-3">
          <Button disabled={saving} onClick={onClose} variant="secondary" className="rounded-full bg-[#f5f5f7] hover:bg-neutral-200">Cancel</Button>
          <Button 
            onClick={save} 
            disabled={isValidationFailed || saving}
            className="rounded-full bg-black px-6 text-white hover:bg-black/90 disabled:opacity-40 disabled:cursor-not-allowed transition-all"
          >
            {saving ? "Saving..." : "Save KPI"}
          </Button>
        </div>
      </motion.div>
    </div>
  );
}


function ContextualInput({ def, draft, setDraft }) {
  if (def.inputType === "calculated_rate") {
    return (
      <div className="grid gap-4 md:grid-cols-2">
        <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">{def.numeratorLabel}</span><input type="number" value={draft.numerator || 0} onChange={(e) => setDraft({ ...draft, numerator: Number(e.target.value) })} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none" /></label>
        <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">{def.denominatorLabel}</span><input type="number" value={draft.denominator || 0} onChange={(e) => setDraft({ ...draft, denominator: Number(e.target.value) })} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none" /></label>
      </div>
    );
  }
  if (def.inputType === "checklist") {
    return (
      <div className="rounded-3xl bg-[#f5f5f7] p-4">
        <div className="mb-3 text-sm font-medium text-[#1d1d1f]">Checklist progress</div>
        <div className="space-y-3">
          {def.checklistItems.map((item, idx) => (
            <label key={item} className="flex items-center gap-3 rounded-2xl bg-white px-4 py-3 text-sm text-[#1d1d1f]">
              <input type="checkbox" checked={Boolean(draft.checklist?.[idx])} onChange={(e) => {
                const next = [...(draft.checklist || [])];
                next[idx] = e.target.checked;
                setDraft({ ...draft, checklist: next });
              }} />
              {item}
            </label>
          ))}
        </div>
      </div>
    );
  }
  if (def.inputType === "status") {
    return <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">Status</span><select value={draft.actual || "On Track"} onChange={(e) => setDraft({ ...draft, actual: e.target.value })} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none"><option>On Track</option><option>Needs Attention</option><option>Off Track</option></select></label>;
  }
  return <label className="grid gap-2"><span className="text-sm font-medium text-[#1d1d1f]">Actual value</span><input type="number" value={draft.actual || 0} onChange={(e) => setDraft({ ...draft, actual: Number(e.target.value) })} className="rounded-2xl bg-[#f5f5f7] px-4 py-3 outline-none" /></label>;
}

function KpiHistory({ roles, entries, selectedRole, setSelectedRole, weeks, kpis }) {
  const [selectedKpi, setSelectedKpi] = useState("kpi-3");
  const def = getDefinition(selectedKpi, kpis);
  const chartData = weeks.filter(w => w.status !== "planned").map((week) => {
    const entry = entries.find((e) => e.weekId === week.id && e.kpiId === selectedKpi);
    return { 
      week: week.label.replace(" June 2026", ""), 
      actual: entry ? Number(computeActual(def, entry) || 0) : 0, 
      target: Number(def.target) || 0, 
      status: entry ? getStatus(def, entry) : "pending" 
    };
  });
  const roleKpis = kpis.filter((k) => selectedRole === "all" || k.roleId === selectedRole);

  return (
    <PageShell
      eyebrow="Quarter trend"
      title="See whether the KPI is actually improving."
      description="A single weekly number can mislead. History shows whether the team is moving in the right direction across the quarter."
    >
      <div className="mb-6 grid gap-4 md:grid-cols-2">
        <select value={selectedRole} onChange={(e) => { setSelectedRole(e.target.value); setSelectedKpi(kpis.filter((k) => e.target.value === "all" || k.roleId === e.target.value)[0]?.id || "kpi-1"); }} className="rounded-full bg-white px-5 py-4 text-sm text-[#1d1d1f] shadow-sm ring-1 ring-black/5 outline-none font-medium">
          <option value="all">All Roles</option>
          {roles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}
        </select>
        <select value={selectedKpi} onChange={(e) => setSelectedKpi(e.target.value)} className="rounded-full bg-white px-5 py-4 text-sm text-[#1d1d1f] shadow-sm ring-1 ring-black/5 outline-none font-medium">
          {roleKpis.map((k) => <option key={k.id} value={k.id}>{k.name}</option>)}
        </select>
      </div>

      <div className="grid gap-5 lg:grid-cols-3">
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm lg:col-span-2">
          <CardContent className="p-6">
            <div className="mb-5 flex items-start justify-between gap-3">
              <div><h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">{def.name}</h2><p className="mt-1 text-sm text-[#6e6e73]">Target vs actual trend · {inputTypeLabel(def)}</p></div>
              <TrendingUp size={20} className="text-[#a1a1a6]" />
            </div>
            <div className="h-80 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <RLineChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="week" tickLine={false} axisLine={false} />
                  <YAxis tickLine={false} axisLine={false} />
                  <Tooltip />
                  <Line type="monotone" dataKey="actual" strokeWidth={3} dot={{ r: 4 }} />
                  <Line type="monotone" dataKey="target" strokeWidth={2} strokeDasharray="5 5" dot={false} />
                </RLineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">Status history</h2>
            <p className="mt-1 text-sm text-[#6e6e73]">Locked weeks are kept as source of truth.</p>
            <div className="mt-5 space-y-3">
              {chartData.map((row, idx) => (
                <div key={row.week} className="flex items-center justify-between rounded-2xl bg-[#f5f5f7] px-4 py-3">
                  <div><div className="text-sm font-medium text-[#1d1d1f]">{row.week}</div><div className="text-xs text-[#6e6e73]">Actual {row.actual} · Target {row.target}</div></div>
                  <StatusPill status={row.status} />
                </div>
              ))}
            </div>
            <div className="mt-5 rounded-3xl bg-neutral-50 p-4 text-sm leading-6 text-[#6e6e73]">
              Historical correction should be possible in the final app, but not as free edit. It should require a correction reason.
            </div>
          </CardContent>
        </Card>
      </div>
    </PageShell>
  );
}

function WeeklyReview({ roles, entries, weekId, setWeekStatus, weeks, kpis, weeklyReviews, setWeeklyReviews }) {
  const rows = getEntriesForWeek(entries, weekId, kpis);
  const week = weeks.find((w) => w.id === weekId);
  const isLocked = week.status === "locked";
  const attention = rows.filter(({ def, entry }) => ["yellow", "red"].includes(getStatus(def, entry)));

  const review = weeklyReviews[weekId] || {
    revenueTotal: "",
    leadsIn: "",
    followUpRate: "",
    conversionNotes: "",
    decisionsMade: "",
    prioritiesNextWeek: "",
  };

  const [saving, setSaving] = useState(false);
  const [success, setSuccess] = useState(false);
  const [errorMsg, setErrorMsg] = useState(null);

  const saveReview = async (shouldLock = false) => {
    if (isLocked) return;
    setSaving(true);
    setErrorMsg(null);
    try {
      const rawRev = review.revenueTotal ? String(review.revenueTotal).replace(/[^0-9]/g, "") : "";
      const revNum = rawRev ? Number(rawRev) : null;
      const leadsNum = review.leadsIn ? Number(review.leadsIn) : null;

      const dbPayload = {
        week_id: weekId,
        revenue_total: revNum,
        leads_in: leadsNum,
        follow_up_rate: review.followUpRate || "",
        conversion_notes: review.conversionNotes || "",
        decisions_made: review.decisionsMade || "",
        priorities_next_week: review.prioritiesNextWeek || "",
        updated_at: new Date().toISOString()
      };

      const { error } = await supabase
        .from("weekly_reviews")
        .upsert(dbPayload, { onConflict: "week_id" });

      if (error) throw error;

      if (shouldLock) {
        await setWeekStatus(weekId, "locked");
      }

      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err) {
      console.error("Failed to save weekly review:", err);
      setErrorMsg(err.message || "Failed to save weekly review.");
    } finally {
      setSaving(false);
    }
  };

  const handleFieldChange = (field, value) => {
    if (isLocked) return;
    setWeeklyReviews((prev) => ({
      ...prev,
      [weekId]: {
        ...review,
        [field]: value,
      },
    }));
  };

  return (
    <PageShell eyebrow="Meeting-ready summary" title="Complete the review, then lock the week." description="After weekly review is completed, the week becomes historical record. This protects quarterly trend data from casual edits.">
      <div className="grid gap-5 lg:grid-cols-3">
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm lg:col-span-2">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">Revenue & Funnel</h2>
            <div className="mt-5 grid gap-4 md:grid-cols-2">
              <InputBlock 
                label="Revenue Total" 
                value={review.revenueTotal} 
                onChange={(val) => handleFieldChange("revenueTotal", val)}
                disabled={isLocked}
              />
              <InputBlock 
                label="Leads In" 
                value={review.leadsIn} 
                onChange={(val) => handleFieldChange("leadsIn", val)}
                disabled={isLocked}
              />
              <InputBlock 
                label="Follow-up Rate" 
                value={review.followUpRate} 
                onChange={(val) => handleFieldChange("followUpRate", val)}
                disabled={isLocked}
              />
              <InputBlock 
                label="Conversion Notes" 
                value={review.conversionNotes} 
                onChange={(val) => handleFieldChange("conversionNotes", val)}
                disabled={isLocked}
              />
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-[30px] border-black/5 bg-black text-white shadow-sm">
          <CardContent className="p-6">
            <div className="text-sm text-white/60">Week status</div>
            <div className="mt-4 text-5xl font-semibold tracking-tight">{isLocked ? "Locked" : "Open"}</div>
            <p className="mt-4 text-sm leading-6 text-white/70">{isLocked ? "This week is protected as historical data." : "Complete review to lock this week's KPI entries."}</p>
          </CardContent>
        </Card>
      </div>
      <div className="mt-6 grid gap-5 lg:grid-cols-2">
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">Discussion points</h2>
            <p className="mt-1 text-sm text-[#6e6e73]">Auto-generated from Yellow/Red KPIs.</p>
            <div className="mt-5 space-y-3">
              {attention.length ? (
                attention.map(({ def, entry }) => {
                  const role = roles.find((r) => r.id === def.roleId);
                  return (
                    <div key={def.id} className="rounded-3xl bg-[#f5f5f7] p-4">
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <div className="text-sm font-semibold text-[#1d1d1f]">{def.name}</div>
                          <div className="mt-1 text-xs text-[#6e6e73]">{role?.name} · {displayFormula(def, entry)}</div>
                        </div>
                        <StatusPill status={getStatus(def, entry)} />
                      </div>
                      <div className="mt-3 text-sm leading-6 text-[#6e6e73]">Blocker: {entry?.blocker}</div>
                      <div className="mt-1 text-sm leading-6 text-[#1d1d1f]">Next: {entry?.nextAction}</div>
                    </div>
                  );
                })
              ) : (
                <div className="rounded-3xl bg-[#f5f5f7] p-4 text-sm text-[#6e6e73] text-center">
                  All KPIs on track! No discussion points generated.
                </div>
              )}
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">Decisions & priorities</h2>
            <div className="mt-5 grid gap-4">
              <textarea 
                rows={5} 
                value={review.decisionsMade} 
                onChange={(e) => handleFieldChange("decisionsMade", e.target.value)}
                disabled={isLocked}
                placeholder="Decisions made during the meeting..."
                className="rounded-3xl bg-[#f5f5f7] p-4 text-sm leading-6 outline-none disabled:opacity-75 disabled:cursor-not-allowed" 
              />
              <textarea 
                rows={5} 
                value={review.prioritiesNextWeek} 
                onChange={(e) => handleFieldChange("prioritiesNextWeek", e.target.value)}
                disabled={isLocked}
                placeholder="Priorities for next week..."
                className="rounded-3xl bg-[#f5f5f7] p-4 text-sm leading-6 outline-none disabled:opacity-75 disabled:cursor-not-allowed" 
              />
              
              {success && (
                <div className="rounded-2xl bg-emerald-50 text-emerald-800 p-3 text-sm ring-1 ring-emerald-100 flex items-center gap-2">
                  <CheckCircle2 size={14} className="text-emerald-600" />
                  Review saved successfully!
                </div>
              )}
              {errorMsg && (
                <div className="rounded-2xl bg-rose-50 text-rose-800 p-3 text-sm ring-1 ring-rose-100 flex items-center gap-2">
                  <CircleAlert size={14} className="text-rose-600" />
                  {errorMsg}
                </div>
              )}

              <div className="flex gap-2">
                <Button 
                  disabled={isLocked || saving} 
                  onClick={() => saveReview(false)} 
                  variant="secondary"
                  className="w-1/2 rounded-full bg-[#f5f5f7] hover:bg-neutral-200"
                >
                  {saving ? "Saving..." : "Save Draft"}
                </Button>
                <Button 
                  disabled={isLocked || saving} 
                  onClick={() => saveReview(true)} 
                  className="w-1/2 rounded-full bg-black text-white hover:bg-black/90 disabled:cursor-not-allowed disabled:bg-neutral-300"
                >
                  <Archive size={16} className="mr-2" /> {isLocked ? "Week Already Locked" : "Complete & Lock"}
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </PageShell>
  );
}

function InputBlock({ label, value, onChange, disabled }) {
  return (
    <label className="grid gap-2">
      <span className="text-sm font-medium text-[#6e6e73]">{label}</span>
      <input 
        value={value || ""} 
        onChange={(e) => onChange && onChange(e.target.value)} 
        disabled={disabled}
        className="rounded-2xl bg-[#f5f5f7] px-4 py-3 text-sm text-[#1d1d1f] outline-none disabled:opacity-75 disabled:cursor-not-allowed" 
      />
    </label>
  );
}

function MonthlyReview({ roles, entries, weeks, kpis, monthlyReviews, setMonthlyReviews }) {
  const [success, setSuccess] = useState(false);
  const [saving, setSaving] = useState(false);
  const [errorMsg, setErrorMsg] = useState(null);
  const historicalWeeks = weeks.filter((w) => w.status !== "planned").map((w) => w.id);
  const rows = historicalWeeks.flatMap((weekId) => getEntriesForWeek(entries, weekId, kpis));
  const blockers = useMemo(() => {
    const counts = {};
    rows.forEach(({ def, entry }) => {
      if (["yellow", "red"].includes(getStatus(def, entry)) && entry?.blocker) counts[entry.blocker] = (counts[entry.blocker] || 0) + 1;
    });
    return Object.entries(counts).sort((a, b) => b[1] - a[1]);
  }, [rows]);

  const handleSave = async () => {
    setSaving(true);
    setErrorMsg(null);
    setSuccess(false);
    try {
      const dbPayload = {
        month_label: "June 2026",
        what_worked: monthlyReviews.whatWorked || "",
        what_needs_improvement: monthlyReviews.whatDidntWork || "",
        focus_areas_next_month: monthlyReviews.prioritiesNextMonth || "",
        updated_at: new Date().toISOString()
      };

      if (monthlyReviews.id) {
        dbPayload.id = monthlyReviews.id;
      }

      const { data, error } = await supabase
        .from("monthly_reviews")
        .upsert(dbPayload, { onConflict: "month_label" })
        .select("*");

      if (error) throw error;

      if (data && data.length > 0) {
        setMonthlyReviews((prev) => ({
          ...prev,
          id: data[0].id
        }));
      }

      setSuccess(true);
      setTimeout(() => setSuccess(false), 4000);
    } catch (err) {
      console.error("Failed to save monthly review:", err);
      setErrorMsg(err.message || "Failed to save monthly review.");
    } finally {
      setSaving(false);
    }
  };

  return (
    <PageShell eyebrow="Monthly reflection" title="Review patterns, not just one-week noise." description="Monthly view uses weekly history to reveal repeated blockers, role health, and quarter-level progress.">
      {success && (
        <motion.div 
          initial={{ opacity: 0, y: -10 }} 
          animate={{ opacity: 1, y: 0 }} 
          className="mb-6 rounded-[20px] bg-emerald-50 text-emerald-800 p-4 text-sm leading-6 ring-1 ring-emerald-200 flex items-center gap-3 shadow-sm"
        >
          <CheckCircle2 size={16} className="text-emerald-600" />
          <span><strong>Reflection saved successfully!</strong> Monthly review logs have been securely locked and archived.</span>
        </motion.div>
      )}
      <div className="grid gap-5 lg:grid-cols-2">
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">KPI summary by role</h2>
            <div className="mt-5 space-y-3">
              {roles.map((role) => {
                const roleRows = rows.filter(({ def }) => def.roleId === role.id);
                const statuses = roleRows.map(({ def, entry }) => getStatus(def, entry));
                return (
                  <div key={role.id} className="rounded-3xl bg-[#f5f5f7] p-4">
                    <div className="mb-3 flex items-center justify-between">
                      <div className="text-sm font-semibold text-[#1d1d1f]">{role.name}</div>
                      <div className="text-xs text-[#6e6e73]">{role.owner}</div>
                    </div>
                    <div className="grid grid-cols-4 gap-3 text-center">
                      <MiniMetric label="Green" value={statuses.filter((s) => s === "green").length} />
                      <MiniMetric label="Yellow" value={statuses.filter((s) => s === "yellow").length} />
                      <MiniMetric label="Red" value={statuses.filter((s) => s === "red").length} />
                      <MiniMetric label="Pending" value={statuses.filter((s) => s === "pending").length} />
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-[30px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-[#1d1d1f]">Repeated blockers</h2>
            <div className="mt-5 space-y-3">
              {blockers.length ? blockers.map(([blocker, count]) => (
                <div key={blocker} className="flex items-center justify-between rounded-2xl bg-[#f5f5f7] px-4 py-3">
                  <span className="text-sm text-[#1d1d1f]">{blocker}</span>
                  <span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-[#6e6e73]">{count}</span>
                </div>
              )) : <div className="rounded-2xl bg-[#f5f5f7] p-4 text-sm text-[#6e6e73]">No blocker recorded this month.</div>}
            </div>
            <div className="mt-6 grid gap-4">
              <label className="grid gap-2">
                <span className="text-sm font-medium text-[#1d1d1f]">What worked?</span>
                <textarea 
                  rows={3} 
                  placeholder="What worked?" 
                  value={monthlyReviews.whatWorked || ""}
                  onChange={(e) => setMonthlyReviews({ ...monthlyReviews, whatWorked: e.target.value })}
                  className="rounded-3xl bg-[#f5f5f7] p-4 text-sm outline-none" 
                />
              </label>
              <label className="grid gap-2">
                <span className="text-sm font-medium text-[#1d1d1f]">What did not work?</span>
                <textarea 
                  rows={3} 
                  placeholder="What did not work?" 
                  value={monthlyReviews.whatDidntWork || ""}
                  onChange={(e) => setMonthlyReviews({ ...monthlyReviews, whatDidntWork: e.target.value })}
                  className="rounded-3xl bg-[#f5f5f7] p-4 text-sm outline-none" 
                />
              </label>
              <label className="grid gap-2">
                <span className="text-sm font-medium text-[#1d1d1f]">Priorities for next month</span>
                <textarea 
                  rows={3} 
                  placeholder="Priorities for next month" 
                  value={monthlyReviews.prioritiesNextMonth || ""}
                  onChange={(e) => setMonthlyReviews({ ...monthlyReviews, prioritiesNextMonth: e.target.value })}
                  className="rounded-3xl bg-[#f5f5f7] p-4 text-sm outline-none" 
                />
              </label>
              {errorMsg && (
                <div className="rounded-2xl bg-rose-50 text-rose-800 p-3 text-sm ring-1 ring-rose-100 flex items-center gap-2">
                  <CircleAlert size={14} className="text-rose-600" />
                  {errorMsg}
                </div>
              )}
              <Button disabled={saving} onClick={handleSave} className="rounded-full bg-black text-white hover:bg-black/90 disabled:bg-neutral-300">
                {saving ? "Saving..." : "Save Monthly Review"}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </PageShell>
  );
}

function MiniMetric({ label, value }) {
  return <div className="rounded-2xl bg-white p-3"><div className="text-lg font-semibold text-[#1d1d1f]">{value}</div><div className="text-[11px] text-[#6e6e73]">{label}</div></div>;
}

function KpiSetup({ roles, kpis, setKpis }) {
  const [editingKpiId, setEditingKpiId] = useState(null);
  const [tempTarget, setTempTarget] = useState("");
  const [success, setSuccess] = useState(false);

  const startEdit = (kpi) => {
    setEditingKpiId(kpi.id);
    setTempTarget(kpi.target.toString());
  };

  const cancelEdit = () => {
    setEditingKpiId(null);
  };

  const saveTarget = async (kpiId) => {
    const kpi = kpis.find(k => k.id === kpiId);
    if (!kpi) return;
    
    const isNum = kpi.inputType !== "status";
    const newTarget = isNum ? Number(tempTarget) : tempTarget;
    
    try {
      const dbPayload = {};
      if (isNum) {
        dbPayload.target_value = newTarget;
      } else {
        dbPayload.target_status = newTarget;
      }
      
      const { error } = await supabase
        .from("kpi_definitions")
        .update(dbPayload)
        .eq("id", kpiId);
        
      if (error) throw error;
      
      setKpis((prev) =>
        prev.map((k) => {
          if (k.id === kpiId) {
            return {
              ...k,
              target: newTarget,
            };
          }
          return k;
        })
      );
      setEditingKpiId(null);
      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err) {
      console.error("Failed to update target in Supabase:", err);
      alert(`Failed to update KPI target: ${err.message}`);
    }
  };

  return (
    <PageShell eyebrow="System settings" title="Define how each KPI should be input." description="The most important v2 change: percentage KPIs are no longer typed manually. They are calculated from operational components.">
      {success && (
        <motion.div 
          initial={{ opacity: 0, y: -10 }} 
          animate={{ opacity: 1, y: 0 }} 
          className="mb-6 rounded-[20px] bg-emerald-50 text-emerald-800 p-4 text-sm leading-6 ring-1 ring-emerald-200 flex items-center gap-3 shadow-sm"
        >
          <CheckCircle2 size={16} className="text-emerald-600" />
          <span><strong>Target updated successfully!</strong> The new KPI thresholds have been applied across all dashboards.</span>
        </motion.div>
      )}
      <Card className="mb-6 rounded-[30px] border-black/5 bg-white shadow-sm">
        <CardContent className="flex items-start gap-4 p-6">
          <div className="rounded-2xl bg-[#f5f5f7] p-3 text-[#6e6e73]"><Settings2 size={20} /></div>
          <div>
            <h2 className="text-lg font-semibold tracking-tight text-[#1d1d1f]">Contextual KPI input</h2>
            <p className="mt-1 text-sm leading-6 text-[#6e6e73]">A rate is only useful if the system stores the numerator and denominator behind it. This keeps KPI review actionable and auditable.</p>
          </div>
        </CardContent>
      </Card>
      <Card className="overflow-hidden rounded-[30px] border-black/5 bg-white shadow-sm">
        <CardContent className="p-0">
          <div className="hidden grid-cols-[1.1fr_1.3fr_1fr_1.1fr_1fr_.6fr] gap-4 border-b border-black/5 px-6 py-4 text-xs font-semibold uppercase tracking-wide text-[#a1a1a6] lg:grid">
            <div>Role</div>
            <div>KPI</div>
            <div>Input type</div>
            <div>Required input</div>
            <div>Target</div>
            <div>Actions</div>
          </div>
          <div className="divide-y divide-black/5">
            {kpis.map((def) => {
              const role = roles.find((r) => r.id === def.roleId);
              const isEditing = editingKpiId === def.id;
              return (
                <div key={def.id} className="grid gap-4 px-6 py-5 lg:grid-cols-[1.1fr_1.3fr_1fr_1.1fr_1fr_.6fr] lg:items-center">
                  <div>
                    <div className="text-sm font-medium text-[#1d1d1f]">{role?.name}</div>
                    <div className="text-xs text-[#6e6e73]">{role?.owner}</div>
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-[#1d1d1f]">{def.name}</div>
                    <div className="mt-1 line-clamp-2 text-xs leading-5 text-[#6e6e73]">{def.description}</div>
                  </div>
                  <div className="text-sm text-[#6e6e73]">{inputTypeLabel(def)}</div>
                  <div className="text-sm leading-6 text-[#1d1d1f]">{def.inputType === "calculated_rate" ? `${def.numeratorLabel} + ${def.denominatorLabel}` : def.inputType === "checklist" ? "Checklist items" : def.inputType === "status" ? "Status" : "Actual value"}</div>
                  <div>
                    {isEditing ? (
                      <div className="flex items-center gap-1.5">
                        {def.inputType === "status" ? (
                          <select 
                            value={tempTarget} 
                            onChange={(e) => setTempTarget(e.target.value)}
                            className="w-full rounded-lg bg-[#f5f5f7] px-2 py-1 text-sm border-0 outline-none"
                          >
                            <option>On Track</option>
                            <option>Needs Attention</option>
                            <option>Off Track</option>
                          </select>
                        ) : (
                          <input 
                            type="number" 
                            value={tempTarget} 
                            onChange={(e) => setTempTarget(e.target.value)}
                            className="w-24 rounded-lg bg-[#f5f5f7] px-2 py-1 text-sm border-0 outline-none font-semibold text-[#1d1d1f]"
                          />
                        )}
                        <span className="text-xs text-[#6e6e73]">{def.unit || ""}</span>
                      </div>
                    ) : (
                      <div className="text-sm font-semibold text-[#1d1d1f]">{formatTarget(def)}</div>
                    )}
                  </div>
                  <div className="flex gap-2">
                    {isEditing ? (
                      <>
                        <button onClick={() => saveTarget(def.id)} className="rounded-full bg-black text-white px-3 py-1 text-xs font-medium hover:bg-black/90">Save</button>
                        <button onClick={cancelEdit} className="rounded-full bg-[#f5f5f7] text-[#6e6e73] px-3 py-1 text-xs font-medium hover:bg-neutral-200">Cancel</button>
                      </>
                    ) : (
                      <button onClick={() => startEdit(def)} className="rounded-full bg-[#f5f5f7] text-[#1d1d1f] px-3 py-1.5 text-xs font-medium hover:bg-neutral-200 flex items-center gap-1"><Edit3 size={11} /> Edit</button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
    </PageShell>
  );
}

function Home({ setActive }) {
  const modules = [
    {
      id: "kpi",
      title: "KPI Tracker",
      status: "Active MVP",
      description: "Weekly KPI transparency, contextual input, history, blocker tracking, and review lock.",
      features: ["Weekly KPI tracking", "Target vs actual history", "Blocker & next action visibility"],
      cta: "Open KPI Dashboard",
      action: () => setActive("dashboard"),
      active: true,
    },
    {
      id: "campaign",
      title: "Campaign Library",
      status: "Planned Module",
      description: "A shared archive for campaigns, experiments, A/B tests, results, and learnings.",
      features: ["Campaign archive", "A/B testing log", "Learning repository"],
      cta: "Planned for next phase",
      action: () => setActive("campaign"),
      active: false,
    },
    {
      id: "business",
      title: "Business Performance History",
      status: "Planned Module",
      description: "Historical view of revenue, product contribution, funnel movement, and quarterly business health.",
      features: ["Revenue by product", "Funnel trend", "Quarterly performance recap"],
      cta: "Planned for next phase",
      action: () => setActive("business"),
      active: false,
    },
    {
      id: "learningJourney",
      title: "Intern Learning Journey",
      status: "Planned Module",
      description: "A structured place to track intern onboarding, learning progress, assignment, and readiness.",
      features: ["Learning milestone", "Assignment tracking", "Readiness progress"],
      cta: "Planned for next phase",
      action: () => setActive("learningJourney"),
      active: false,
    },
  ];

  return (
    <PageShell
      eyebrow="B2C Growth Operating System"
      title="One operating surface for B2C growth discipline."
      description="The MVP focuses deeply on KPI tracking, while the product architecture already prepares future modules for campaign learning, business performance, and intern development."
    >
      <div className="mb-8 grid gap-4 md:grid-cols-3">
        <StatCard label="Active MVP Module" value="KPI Tracker" caption="Built and usable first" icon={CheckCircle2} />
        <StatCard label="Planned Modules" value="3" caption="Prepared as front-end shell" icon={Archive} />
        <StatCard label="Product Principle" value="No Overkill" caption="Build only what the team will use now" icon={Sparkles} />
      </div>

      <div className="grid gap-5 lg:grid-cols-4">
        {modules.map((module) => (
          <Card key={module.id} className={`rounded-[32px] border-black/5 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md ${module.active ? "ring-1 ring-black/10" : ""}`}>
            <CardContent className="flex h-full flex-col p-6">
              <div className="mb-5 flex items-start justify-between gap-3">
                <div>
                  <div className="text-lg font-semibold tracking-tight text-[#1d1d1f]">{module.title}</div>
                  <div className="mt-2 text-sm leading-6 text-[#6e6e73]">{module.description}</div>
                </div>
                <span className={`shrink-0 rounded-full px-3 py-1 text-xs font-medium ring-1 ${module.active ? "bg-emerald-50 text-emerald-700 ring-emerald-100" : "bg-neutral-100 text-neutral-500 ring-neutral-200"}`}>
                  {module.status}
                </span>
              </div>

              <div className="mt-auto rounded-3xl bg-[#f5f5f7] p-4">
                <div className="mb-3 text-xs font-medium uppercase tracking-wide text-[#a1a1a6]">Module scope</div>
                <div className="space-y-2">
                  {module.features.map((feature) => (
                    <div key={feature} className="flex items-center gap-2 text-sm text-[#1d1d1f]">
                      <CheckCircle2 size={14} className={module.active ? "text-emerald-600" : "text-[#a1a1a6]"} />
                      {feature}
                    </div>
                  ))}
                </div>
              </div>

              <Button onClick={module.action} className={`mt-5 w-full rounded-full ${module.active ? "bg-black text-white hover:bg-black/90" : "bg-[#f5f5f7] text-[#6e6e73] hover:bg-neutral-200"}`}>
                {module.cta}
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card className="mt-8 rounded-[32px] border-black/5 bg-black text-white shadow-sm">
        <CardContent className="p-7">
          <div className="grid gap-6 md:grid-cols-[1.2fr_.8fr] md:items-center">
            <div>
              <div className="text-sm text-white/60">MVP strategy</div>
              <h2 className="mt-2 text-2xl font-semibold tracking-tight">Build the habit first. Expand the system later.</h2>
              <p className="mt-3 text-sm leading-6 text-white/70">KPI Tracker is the only functional module in this MVP because weekly transparency is the current bottleneck. Other modules are visible to show product direction without increasing development scope.</p>
            </div>
            <div className="rounded-3xl bg-white/10 p-5 text-sm leading-7 text-white/75">
              Current priority: KPI clarity, weekly history, blocker visibility, and review discipline. Campaign Library and other modules should only become functional after KPI tracking is adopted consistently.
            </div>
          </div>
        </CardContent>
      </Card>
    </PageShell>
  );
}

function PlannedModulePage({ title, subtitle, features, setActive }) {
  return (
    <PageShell
      eyebrow="Planned module"
      title={title}
      description={subtitle}
    >
      <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]">
        <Card className="rounded-[32px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-7">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-neutral-100 px-4 py-2 text-sm font-medium text-[#6e6e73] ring-1 ring-neutral-200">
              <Lock size={15} /> Not available in MVP
            </div>
            <h2 className="text-2xl font-semibold tracking-tight text-[#1d1d1f]">This module is intentionally kept as a shell.</h2>
            <p className="mt-3 max-w-2xl text-sm leading-7 text-[#6e6e73]">The front-end prepares the product architecture, but the system logic is not built yet. This keeps the MVP focused on KPI tracking while making the long-term direction clear.</p>
            <div className="mt-7 grid gap-3 md:grid-cols-3">
              {features.map((feature) => (
                <div key={feature} className="rounded-3xl bg-[#f5f5f7] p-4">
                  <CheckCircle2 size={18} className="mb-3 text-[#a1a1a6]" />
                  <div className="text-sm font-medium leading-6 text-[#1d1d1f]">{feature}</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-[32px] border-black/5 bg-white shadow-sm">
          <CardContent className="p-7">
            <div className="text-sm text-[#6e6e73]">Recommended next step</div>
            <h3 className="mt-2 text-xl font-semibold tracking-tight text-[#1d1d1f]">Do not build this yet.</h3>
            <p className="mt-3 text-sm leading-7 text-[#6e6e73]">Validate KPI Tracker adoption for 3–4 weeks first. Once weekly tracking becomes consistent, prioritize the next module based on the most painful workflow.</p>
            <Button onClick={() => setActive("dashboard")} className="mt-6 w-full rounded-full bg-black text-white hover:bg-black/90">
              Back to Active MVP
            </Button>
          </CardContent>
        </Card>
      </div>
    </PageShell>
  );
}

export default function B2CKPIDashboardPrototype() {
  const [active, setActive] = useState("home");
  const [weekId, setWeekId] = useState("w3");
  const [roles, setRoles] = useState([]);
  const [entries, setEntries] = useState([]);
  const [selectedRole, setSelectedRole] = useState("all");
  const [weeks, setWeeks] = useState([]);
  const [kpis, setKpis] = useState([]);
  const [weeklyReviews, setWeeklyReviews] = useState({});
  const [monthlyReviews, setMonthlyReviews] = useState({
    whatWorked: "",
    whatDidntWork: "",
    prioritiesNextMonth: ""
  });
  
  const [loading, setLoading] = useState(true);
  const [dbError, setDbError] = useState(null);
  const [actionError, setActionError] = useState(null);

  const fetchData = async () => {
    setLoading(true);
    setDbError(null);
    try {
      if (!supabase) {
        throw new Error("Supabase client is not initialized. Please verify that VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are correctly configured as environment variables in your Netlify settings, and then trigger a new deploy.");
      }
      const { data: dbRoles, error: rolesError } = await supabase.from("roles").select("*").order("name");
      if (rolesError) throw rolesError;
      
      const { data: dbWeeks, error: weeksError } = await supabase.from("weeks").select("*").order("created_at");
      if (weeksError) throw weeksError;
      
      const { data: dbKpis, error: kpisError } = await supabase.from("kpi_definitions").select("*");
      if (kpisError) throw kpisError;

      const { data: dbEntries, error: entriesError } = await supabase.from("kpi_entries").select("*");
      if (entriesError) throw entriesError;

      const { data: dbWeekly, error: weeklyError } = await supabase.from("weekly_reviews").select("*");
      if (weeklyError) throw weeklyError;

      const { data: dbMonthly, error: monthlyError } = await supabase.from("monthly_reviews").select("*").order("created_at", { ascending: false });
      if (monthlyError) throw monthlyError;

      setRoles(dbRoles);

      const mappedWeeks = dbWeeks.map(w => ({
        id: w.id,
        label: w.label,
        status: w.status,
        quarterWeek: w.quarter_week
      }));
      setWeeks(mappedWeeks);

      const mappedKpis = dbKpis.map(k => ({
        id: k.id,
        roleId: k.role_id,
        name: k.name,
        description: k.description,
        inputType: k.input_type,
        displayType: k.display_type,
        target: k.input_type === 'status' ? k.target_status : Number(k.target_value),
        unit: k.unit,
        numeratorLabel: k.numerator_label,
        denominatorLabel: k.denominator_label,
        checklistItems: k.checklist_items || []
      }));
      setKpis(mappedKpis);

      const mappedEntries = dbEntries.map(e => {
        const def = mappedKpis.find(k => k.id === e.kpi_id);
        return {
          id: e.id,
          weekId: e.week_id,
          kpiId: e.kpi_id,
          actual: def?.inputType === 'status' ? e.actual_status : (e.actual_value !== null ? Number(e.actual_value) : null),
          numerator: e.numerator_value !== null ? Number(e.numerator_value) : null,
          denominator: e.denominator_value !== null ? Number(e.denominator_value) : null,
          checklist: e.checklist_values || null,
          notes: e.notes,
          blocker: e.blocker,
          nextAction: e.next_action,
          updatedBy: e.updated_by,
          updatedAt: e.updated_at
        };
      });
      setEntries(mappedEntries);

      const mappedWeekly = {};
      dbWeekly.forEach(r => {
        mappedWeekly[r.week_id] = {
          revenueTotal: r.revenue_total !== null ? `Rp${Number(r.revenue_total).toLocaleString('id-ID')}` : "",
          leadsIn: r.leads_in !== null ? String(r.leads_in) : "",
          followUpRate: r.follow_up_rate || "",
          conversionNotes: r.conversion_notes || "",
          decisionsMade: r.decisions_made || "",
          prioritiesNextWeek: r.priorities_next_week || ""
        };
      });
      setWeeklyReviews(mappedWeekly);

      if (dbMonthly && dbMonthly.length > 0) {
        const m = dbMonthly[0];
        setMonthlyReviews({
          id: m.id,
          whatWorked: m.what_worked || "",
          whatDidntWork: m.what_needs_improvement || "",
          prioritiesNextMonth: m.focus_areas_next_month || ""
        });
      } else {
        setMonthlyReviews({
          whatWorked: "",
          whatDidntWork: "",
          prioritiesNextMonth: ""
        });
      }
      
      const currentWeek = mappedWeeks.find(w => w.status === 'current');
      if (currentWeek) {
        setWeekId(currentWeek.id);
      } else if (mappedWeeks.length > 0) {
        setWeekId(mappedWeeks[0].id);
      }
    } catch (err) {
      console.error("Error loading data from Supabase:", err);
      setDbError(err.message || "Failed to sync with database.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  async function setWeekStatus(id, status) {
    setActionError(null);
    try {
      const { error } = await supabase
        .from("weeks")
        .update({ status })
        .eq("id", id);
      
      if (error) throw error;
      
      setWeeks((prev) =>
        prev.map((w) => (w.id === id ? { ...w, status } : w))
      );
    } catch (err) {
      console.error("Failed to update week status in Supabase:", err);
      setActionError(`Failed to update week status: ${err.message}`);
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-[#f5f5f7] font-sans text-[#1d1d1f]">
        <div className="relative flex flex-col items-center">
          <div className="h-10 w-10 animate-spin rounded-full border-2 border-black/5 border-t-black" />
          <div className="mt-5 text-sm font-medium tracking-tight text-[#1d1d1f]">Syncing with Supabase...</div>
          <div className="mt-1.5 text-xs text-[#86868b]">Securing live growth metrics</div>
        </div>
      </div>
    );
  }

  if (dbError) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-[#f5f5f7] font-sans p-6 text-center">
        <div className="max-w-md rounded-[32px] bg-white p-8 shadow-sm ring-1 ring-black/5">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-rose-50 text-rose-600">
            <CircleAlert size={24} />
          </div>
          <h2 className="mt-5 text-xl font-semibold tracking-tight text-[#1d1d1f]">Database Connection Failed</h2>
          <p className="mt-3 text-sm leading-6 text-[#6e6e73]">
            We encountered an error syncing with Supabase: <code className="block mt-2 rounded-xl bg-neutral-100 p-2.5 text-xs text-rose-600 font-mono break-all">{dbError}</code>
          </p>
          <button 
            onClick={fetchData} 
            className="mt-6 rounded-full bg-black text-white px-5 py-2.5 text-sm font-medium hover:bg-black/90 transition"
          >
            Retry Connection
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#f5f5f7] font-sans text-[#1d1d1f]">
      <Header active={active} setActive={setActive} weekId={weekId} setWeekId={setWeekId} weeks={weeks} />
      {actionError && (
        <div className="mx-auto mt-4 max-w-7xl px-6">
          <div className="rounded-[20px] bg-rose-50 text-rose-800 p-4 text-sm leading-6 ring-1 ring-rose-200 flex items-center justify-between shadow-sm">
            <div className="flex items-center gap-3">
              <CircleAlert size={16} className="text-rose-600" />
              <span><strong>Action Failed:</strong> {actionError}</span>
            </div>
            <button onClick={() => setActionError(null)} className="text-rose-500 hover:text-rose-700 font-medium">Dismiss</button>
          </div>
        </div>
      )}
      {active === "home" && <Home setActive={setActive} />}
      {active === "dashboard" && <Dashboard roles={roles} entries={entries} weekId={weekId} setActive={setActive} setSelectedRole={setSelectedRole} weeks={weeks} kpis={kpis} />}
      {active === "tracking" && <KpiTracking roles={roles} entries={entries} setEntries={setEntries} weekId={weekId} selectedRole={selectedRole} setSelectedRole={setSelectedRole} weeks={weeks} kpis={kpis} />}
      {active === "history" && <KpiHistory roles={roles} entries={entries} selectedRole={selectedRole} setSelectedRole={setSelectedRole} weeks={weeks} kpis={kpis} />}
      {active === "weekly" && <WeeklyReview roles={roles} entries={entries} weekId={weekId} setWeekStatus={setWeekStatus} weeks={weeks} kpis={kpis} weeklyReviews={weeklyReviews} setWeeklyReviews={setWeeklyReviews} />}
      {active === "campaign" && <PlannedModulePage title="Campaign Library" subtitle="A future module for campaign archive, A/B testing history, creative learning, and post-campaign evaluation." features={["Campaign archive", "A/B test tracker", "Result and learning log"]} setActive={setActive} />}
      {active === "business" && <PlannedModulePage title="Business Performance History" subtitle="A future module for product revenue history, funnel trend, business performance recap, and quarterly growth view." features={["Revenue by product", "Funnel performance trend", "Quarterly business recap"]} setActive={setActive} />}
      {active === "learningJourney" && <PlannedModulePage title="Intern Learning Journey" subtitle="A future module for intern onboarding, learning milestones, assignment visibility, and readiness tracking." features={["Learning milestones", "Assignment progress", "Readiness evaluation"]} setActive={setActive} />}
      {active === "monthly" && <MonthlyReview roles={roles} entries={entries} weeks={weeks} kpis={kpis} monthlyReviews={monthlyReviews} setMonthlyReviews={setMonthlyReviews} />}
      {active === "setup" && <KpiSetup roles={roles} kpis={kpis} setKpis={setKpis} />}
      <div className="mx-auto max-w-7xl px-6 pb-10 text-center text-xs text-[#a1a1a6]">
        Prototype v3 · B2C Growth Operating System shell · KPI Tracker active MVP · Planned modules prepared
      </div>
    </div>
  );
}
